env:
  global:
    - CC_TEST_REPORTER_ID=0004fa134816e5d29d9b8905dd359086880db44e00fa9cf4d3050eda3c78123b
language: python
python:
  - "3.6.2"
cache: pip
#install:
#  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build  
script:
  - python test_run.py
  - coverage run test_run.py
after_script:
  - ./cc-test-reporter after-build --exit-code 0  
after_success: 
  - coveralls 
